export const LANDING_PAGE_TAB_VALUES= {
    NORMAL: "NORMAL",
    LAST_CHANCE: "LAST_CHANCE",
    TOP_RATED: "TOP_RATED"
}

export const ITEM_PAGE_TAB_VALUES= {
    DETAILS: "DETAILS",
    SELLER_INFO: "SELLER_INFO",
    CUSTOMER_REVIEWS: "CUSTOMER_REVIEWS"
}